load(
    "@rules_scala_annex//rules:scala.bzl",
    "scala_binary",
    "scala_test",
)

scala_binary(
    name = "is_sorted",
    srcs = [
        "IsSorted.scala",
    ],
)

scala_binary(
    name = "fibonacci",
    srcs = [
        "Fibonacci.scala",
    ],
)

scala_binary(
    name = "currying",
    srcs = [
        "Currying.scala",
    ],
)

scala_binary(
    name = "composition",
    srcs = [
        "Composition.scala",
    ],
)
