load(
    "@rules_scala_annex//rules:scala.bzl",
    "scala_binary",
)

scala_binary(
    name = "option",
    srcs = [
        "MyOption.scala",
    ],
)

scala_binary(
    name = "either",
    srcs = [
        "MyEither.scala",
    ],
)
