load(
    "@rules_scala_annex//rules:scala.bzl",
    "scala_binary",
)

scala_binary(
    name = "list",
    srcs = [
        "List.scala",
    ],
)

scala_binary(
    name = "tree",
    srcs = [
        "Tree.scala",
    ],
)
